import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { viteSingleFile } from "vite-plugin-singlefile";
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

/* ------------------------------------------------------------------
   Build output: a single self-contained dist/index.html (JS + CSS + SVG +
   SRT inlined) plus dist/audio/*.mp3, the web-app manifest, icons and a
   hand-written service worker (sw.js, generated below).

   Installed to an iPad's home screen it runs fully offline: on first
   load the service worker downloads *every* file in dist/ into a cache
   named after the build hash; later loads are served from that cache,
   including audio with HTTP Range requests (Safari needs 206 replies
   for <audio> seeking). A new build gets a new hash → new cache; the old
   one is deleted once the new worker activates.
   ------------------------------------------------------------------ */

function listFiles(dir, base = dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...listFiles(p, base));
    else out.push(relative(base, p).split("\\").join("/"));
  }
  return out;
}

function offlineServiceWorker() {
  let outDir = "dist";
  return {
    name: "rtmss-offline-sw",
    apply: "build",
    configResolved(c) { outDir = c.build.outDir; },
    closeBundle() {
      const files = listFiles(outDir).filter((f) => f !== "sw.js");
      const hash = createHash("md5");
      for (const f of files) hash.update(f).update(readFileSync(join(outDir, f)));
      const build = hash.digest("hex").slice(0, 12);
      const sw = SW_TEMPLATE
        .replace("__BUILD__", build)
        .replace("__ASSETS__", JSON.stringify(files));
      writeFileSync(join(outDir, "sw.js"), sw);
      console.log(`\n[offline-sw] sw.js written — build ${build}, ${files.length} files precached`);
    }
  };
}

const SW_TEMPLATE = `/* generated by vite.config.js — do not edit */
const BUILD = "__BUILD__";
const CACHE = "rtmss-" + BUILD;
const ASSETS = __ASSETS__;
const SCOPE = self.registration.scope;
const url = (p) => new URL(p, SCOPE).href;
const INDEX = url("index.html");

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache: "reload" bypasses the HTTP cache so a fresh build is really fetched
    await Promise.all(ASSETS.map((p) => cache.add(new Request(url(p), { cache: "reload" }))));
    await self.skipWaiting();
  })());
});

/* self-healing: re-fetch any listed file that is missing from the cache
   (e.g. after storage pressure) — called on activate and on cache misses */
async function ensureAll() {
  const cache = await caches.open(CACHE);
  const have = new Set((await cache.keys()).map((r) => r.url));
  const missing = ASSETS.filter((p) => !have.has(url(p)));
  await Promise.all(missing.map((p) => cache.add(new Request(url(p), { cache: "reload" })).catch(() => {})));
  return missing.length;
}

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    const hadOld = keys.some((k) => k.startsWith("rtmss-") && k !== CACHE);
    await Promise.all(keys.filter((k) => k.startsWith("rtmss-") && k !== CACHE).map((k) => caches.delete(k)));
    await ensureAll();
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: "window" });
    for (const c of clients) c.postMessage({ type: "SW_READY", build: BUILD, updated: hadOld });
  })());
});

/* Safari asks for media with Range headers and expects 206 replies */
async function rangeResponse(request, full) {
  const range = request.headers.get("range");
  const m = /bytes=(\\d*)-(\\d*)/.exec(range || "");
  const buf = await full.arrayBuffer();
  const size = buf.byteLength;
  let start = m && m[1] !== "" ? parseInt(m[1], 10) : 0;
  let end = m && m[2] !== "" ? parseInt(m[2], 10) : size - 1;
  if (m && m[1] === "" && m[2] !== "") { start = Math.max(0, size - parseInt(m[2], 10)); end = size - 1; }
  end = Math.min(end, size - 1);
  if (start > end || start >= size) {
    return new Response(null, { status: 416, headers: { "Content-Range": "bytes */" + size } });
  }
  const headers = new Headers(full.headers);
  headers.set("Content-Range", "bytes " + start + "-" + end + "/" + size);
  headers.set("Content-Length", String(end - start + 1));
  headers.set("Accept-Ranges", "bytes");
  return new Response(buf.slice(start, end + 1), { status: 206, statusText: "Partial Content", headers });
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const u = new URL(req.url);
  if (u.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // navigations → the app shell
    if (req.mode === "navigate") {
      const shell = await cache.match(INDEX);
      if (shell) return shell;
      return fetch(req);
    }
    const cached = await cache.match(u.href, { ignoreSearch: true });
    if (cached) {
      return req.headers.has("range") ? rangeResponse(req, cached) : cached;
    }
    // listed but missing (cache was partially evicted): fetch, store, heal the rest
    const rel = u.href.startsWith(SCOPE) ? u.href.slice(SCOPE.length).split("?")[0] : null;
    const res = await fetch(req);
    if (rel && ASSETS.includes(rel) && res.ok && res.status === 200) {
      cache.put(u.href, res.clone()).catch(() => {});
      ensureAll();
    }
    return res;
  })());
});

self.addEventListener("message", (e) => {
  if (!e.data) return;
  if (e.data.type === "CHECK") {
    e.waitUntil(ensureAll().then((n) => e.source && e.source.postMessage({ type: "SW_CHECKED", healed: n })));
  } else if (e.data.type === "STATUS") {
    e.waitUntil((async () => {
      const cache = await caches.open(CACHE);
      const have = new Set((await cache.keys()).map((r) => r.url));
      const cached = ASSETS.filter((p) => have.has(url(p))).length;
      if (e.source) e.source.postMessage({ type: "SW_STATUS", total: ASSETS.length, cached, build: BUILD });
    })());
  }
});
`;

export default defineConfig({
  base: "./",
  plugins: [react(), viteSingleFile(), offlineServiceWorker()],
  build: {
    target: "es2018",
    cssCodeSplit: false,
    assetsInlineLimit: 100000000,
    reportCompressedSize: false
  },
  server: { port: 5173, strictPort: true, host: "127.0.0.1" }
});
